export const presetMetadata = {
  scenes: {
    "hero-side-by-side": {
      name: "hero-side-by-side",
      type: "scene",
      status: "stable",
      phase: "layout",
      requires: [".scene__inner", '[data-animate="title"]', '[data-animate="media"]'],
      targets: ["section.scene"],
      affectsLayout: true,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Two-column fullscreen scene.",
    },
    "hero-centered": {
      name: "hero-centered",
      type: "scene",
      status: "stable",
      phase: "layout",
      requires: [".scene__inner", '[data-animate="title"]'],
      targets: ["section.scene"],
      affectsLayout: true,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Centered fullscreen scene.",
    },
    "image-fullscreen": {
      name: "image-fullscreen",
      type: "scene",
      status: "stable",
      phase: "layout",
      requires: [".scene__inner", '[data-animate="media"]'],
      targets: ["section.scene"],
      affectsLayout: true,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Fullscreen media-led scene.",
    },
    "text-media-scroll": {
      name: "text-media-scroll",
      type: "scene",
      status: "stable",
      phase: "layout",
      requires: [".scene__inner", '[data-animate="title"]', '[data-animate="media"]'],
      targets: ["section.scene"],
      affectsLayout: true,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Text and media scene intended for pinned-scroll storytelling.",
    },
  },

  transitions: {
    "normal-scroll": {
      name: "normal-scroll",
      type: "transition",
      status: "stable",
      phase: "scroll",
      requires: ["ScrollTrigger"],
      targets: ["section.scene"],
      affectsLayout: false,
      allowedInTransitions: [],
      risks: [],
      notes: 'Runs enter animation at ScrollTrigger start "top 80%".',
    },
    "pinned-scroll": {
      name: "pinned-scroll",
      type: "transition",
      status: "stable",
      phase: "scroll",
      requires: ["ScrollTrigger"],
      targets: ["section.scene"],
      affectsLayout: true,
      allowedInTransitions: [],
      risks: [],
      notes: "Pins only the current scene, then releases without running exits.",
    },
    "cover-safe": {
      name: "cover-safe",
      type: "transition",
      status: "experimental-beta",
      phase: "composition",
      requires: ["ScrollTrigger", "nextSceneEl"],
      targets: ["section.scene", "next section.scene"],
      affectsLayout: true,
      allowedInTransitions: [],
      risks: [
        "Experimental stacking can expose visual gaps if the next scene does not cover the viewport",
      ],
      notes: "Composes current and next scenes. Experimental beta transition for isolated demos and controlled content only.",
    },
  },

  enterAnimations: {
    "fade-up": {
      name: "fade-up",
      type: "enter-animation",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ["[data-animate]"],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "",
    },
    "fade-up-top": {
      name: "fade-up-top",
      type: "enter-animation",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ["[data-animate]"],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Enters from above toward natural position.",
    },
    "mask-up": {
      name: "mask-up",
      type: "enter-animation",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ['[data-animate="title"]', '[data-animate="text"]'],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: ["Needs clipping wrapper when visible masking is required"],
      notes: "",
    },
    "scale-in": {
      name: "scale-in",
      type: "enter-animation",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ['[data-animate="media"]'],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "",
    },
  },

  exitAnimations: {
    "fade-out": {
      name: "fade-out",
      type: "exit-animation",
      status: "disabled",
      phase: "exit",
      requires: [],
      targets: ["section.scene"],
      affectsLayout: false,
      allowedInTransitions: [],
      risks: ["Can create black gaps in pinned scenes if no next scene is visible"],
      notes: "Kept in code but not instantiated in stable runtime.",
    },
    "slide-out-left": {
      name: "slide-out-left",
      type: "exit-animation",
      status: "disabled",
      phase: "exit",
      requires: [],
      targets: ["section.scene"],
      affectsLayout: false,
      allowedInTransitions: [],
      risks: ["Can create black gaps in pinned scenes if no next scene is visible"],
      notes: "Kept in code but not instantiated in stable runtime.",
    },
    "slide-out-up": {
      name: "slide-out-up",
      type: "exit-animation",
      status: "disabled",
      phase: "exit",
      requires: [],
      targets: ["section.scene"],
      affectsLayout: false,
      allowedInTransitions: [],
      risks: ["Can create black gaps in pinned scenes if no next scene is visible"],
      notes: "Kept in code but not instantiated in stable runtime.",
    },
  },

  childMotions: {
    "fade-up": {
      name: "fade-up",
      type: "child-motion",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ["[data-motion='fade-up']"],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Compatibility child motion matching fade-up enter behavior.",
    },
    "mask-up": {
      name: "mask-up",
      type: "child-motion",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ["[data-motion='mask-up']"],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: ["Needs clipping wrapper when visible masking is required"],
      notes: "Compatibility child motion matching mask-up enter behavior.",
    },
    "image-zoom-out": {
      name: "image-zoom-out",
      type: "child-motion",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ['[data-animate="media"][data-motion="image-zoom-out"]'],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "Media enter motion that does not depend on pinning.",
    },
    "image-parallax-soft": {
      name: "image-parallax-soft",
      type: "child-motion",
      status: "experimental",
      phase: "pinned",
      requires: [".scene__media-inner"],
      targets: ['[data-animate="media"][data-motion="image-parallax-soft"] .scene__media-inner'],
      affectsLayout: false,
      allowedInTransitions: ["pinned-scroll"],
      risks: ["Can create visual gaps if wrapper contract is missing"],
      notes: "Runs inside the existing pinned-scroll timeline.",
    },
    "text-stagger-up": {
      name: "text-stagger-up",
      type: "child-motion",
      status: "stable",
      phase: "enter",
      requires: [],
      targets: ['[data-animate="title"]', '[data-animate="text"]', '[data-animate="cta"]'],
      affectsLayout: false,
      allowedInTransitions: ["normal-scroll", "pinned-scroll"],
      risks: [],
      notes: "",
    },
  },
};
